ALTER TABLE balance DROP CONSTRAINT IF EXISTS fk_order_id;

ALTER TABLE orders DROP COLUMN IF EXISTS order_number;

ALTER TABLE orders ALTER COLUMN id DROP DEFAULT;
ALTER TABLE orders ALTER COLUMN id TYPE BIGINT;

DROP SEQUENCE IF EXISTS orders_id_seq;

ALTER TABLE balance ALTER COLUMN order_id TYPE BIGINT;
ALTER TABLE balance ADD CONSTRAINT fk_order_id FOREIGN KEY (order_id) REFERENCES orders(id);
