// Code generated by MockGen. DO NOT EDIT.
// Source: external_accrual_repository.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockExternalAccrualRepository is a mock of ExternalAccrualRepository interface.
type MockExternalAccrualRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExternalAccrualRepositoryMockRecorder
}

// MockExternalAccrualRepositoryMockRecorder is the mock recorder for MockExternalAccrualRepository.
type MockExternalAccrualRepositoryMockRecorder struct {
	mock *MockExternalAccrualRepository
}

// NewMockExternalAccrualRepository creates a new mock instance.
func NewMockExternalAccrualRepository(ctrl *gomock.Controller) *MockExternalAccrualRepository {
	mock := &MockExternalAccrualRepository{ctrl: ctrl}
	mock.recorder = &MockExternalAccrualRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalAccrualRepository) EXPECT() *MockExternalAccrualRepositoryMockRecorder {
	return m.recorder
}

// GetScroing mocks base method.
func (m *MockExternalAccrualRepository) GetScroing(ctx context.Context, orderNumber string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScroing", ctx, orderNumber)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScroing indicates an expected call of GetScroing.
func (mr *MockExternalAccrualRepositoryMockRecorder) GetScroing(ctx, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScroing", reflect.TypeOf((*MockExternalAccrualRepository)(nil).GetScroing), ctx, orderNumber)
}
