// Code generated by MockGen. DO NOT EDIT.
// Source: external_accrual_repository.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	models "github.com/Sorrowful-free/gopher-market-loyalty-service/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockExternalAccrualRepository is a mock of ExternalAccrualRepository interface.
type MockExternalAccrualRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExternalAccrualRepositoryMockRecorder
}

// MockExternalAccrualRepositoryMockRecorder is the mock recorder for MockExternalAccrualRepository.
type MockExternalAccrualRepositoryMockRecorder struct {
	mock *MockExternalAccrualRepository
}

// NewMockExternalAccrualRepository creates a new mock instance.
func NewMockExternalAccrualRepository(ctrl *gomock.Controller) *MockExternalAccrualRepository {
	mock := &MockExternalAccrualRepository{ctrl: ctrl}
	mock.recorder = &MockExternalAccrualRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalAccrualRepository) EXPECT() *MockExternalAccrualRepositoryMockRecorder {
	return m.recorder
}

// GetScoring mocks base method.
func (m *MockExternalAccrualRepository) GetScoring(ctx context.Context, orderNumber string) (models.ScoringModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScoring", ctx, orderNumber)
	ret0, _ := ret[0].(models.ScoringModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScoring indicates an expected call of GetScoring.
func (mr *MockExternalAccrualRepositoryMockRecorder) GetScoring(ctx, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScoring", reflect.TypeOf((*MockExternalAccrualRepository)(nil).GetScoring), ctx, orderNumber)
}
